### ISSUE TITLE
"meter" event not firing

### ISSUE THREAD

**Issue by danielneal** [react-native-audio-toolkit/react-native-audio-toolkit#258]
I've just set up a basic use of a recorder and player as described in the docs. 

I added a meteringInterval to the options, like so, but the callback is not being called. 

```
let rec = new Recorder("filename.mp4", { meteringInterval: 250 })
    .on("meter", (data) => alert(data))
    .record();
```

I'm on iOS, React Native 0.63.4. 

Is this a bug or have I missed something?

**Comment by danielneal** [comment]
Ah, it's just because the version with the metering is unreleased.

**Comment by mstange22** [comment]
@danielneal - did you resolve this?  I tried to install direct from GitHub, but I got version 1.06.  Did you end up forking and installing to get metering?  I'm using a Voice lib, but would prefer to just use this repo since I'm using it to record and playback.

**Comment by fakhergh** [comment]
@mstange22 the version with metering is not published yet. don't waste your time trying to get it from other branches while it is not exists.

**Comment by mstange22** [comment]
Thank you.  I'm working on forking / releasing my own version with metering.

**Comment by fakhergh** [comment]
@mstange22  Great it up.
Keep me posted after finishing it if you don't mind.

**Comment by fakhergh** [comment]
@mstange22  Great, keep it up.
Please don't forget to keep me posted after finishing it if you don't mind.

**Comment by mstange22** [comment]
@fakhergh I forked and released for our org, but I don't know that I'm crazy about the way it's metering.  -160 means silence?  I can normalize, but it's not the metering level I was hoping for.  I guess I should have seen that in the docs.  I'm currently using a voice recognition library to measure level changes which is working for my application.  I was just trying to avoid bringing in a second library just for that.  But at least it's working.  I may try just a smaller mic level lib (maybe the one the metering working is based on) to avoid requiring voice.  Curious, is there a reason the metering work is not released?  Looks like it's been a couple of years since 2.0.3 was released.
